project:
  type: website
  output-dir: docs
  render:
    - "!drafts/"
    - "*.qmd"

website:
  title: "Data Science for Biology"
  page-navigation: true
  
  navbar:
    logo: "images/DRP_Logo_only_square_transparent.png"
    left:
      - href: index.qmd
        text: Home
      - href: start.qmd
        text: Getting Started

  sidebar:
    style: "floating"
    collapse-level: 1
    accordion: true
    contents:
      - section: "<img src='images/R_logo.png' width='20px' style='margin-right: 5px;'> 1: R and RStudio"
        contents:
          - href: 01-Setup.qmd
            text: Setup
          - href: 01-IntroR.qmd
            text: Introduction to R
          - href: 01-Programming.qmd
            text: Programming in R
          - href: 01-HW.qmd
            text: Homework exercise
      - section: "<img src='images/tidyverse_logo.png' width='20px' style='margin-right: 5px;'> 2: Tidyverse"
        contents:
          - href: 02-Setup.qmd
            text: Setup
          - href: 02-tidyverse.qmd
            text: Tidy data
          - href: 02-dplyr.qmd
            text: Data manipulation
          - href: 02-ggplot2.qmd
            text: Data visualisation
          - href: 02-HW.qmd
            text: Homework exercise
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
